# Generated by Django 4.1.1 on 2022-09-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webscrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('twenty_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('seven_days', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('volume', models.CharField(blank=True, max_length=150)),
                ('circulating_supply', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'tbl_webscapes_data',
            },
        ),
    ]
