# Generated by Django 4.1.1 on 2022-09-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='webscrap',
            table='tbl_webscapes',
        ),
    ]
