# Generated by Django 4.1.1 on 2022-09-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapes_data_app', '0002_alter_webscrap_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webscrap',
            name='circulating_supply',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='hour',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='market_cap',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='seven_days',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='twenty_hours',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='webscrap',
            name='volume',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
